### Prostate Cancer

In [10]:
import pandas as pd
import numpy as np

In [11]:
prostate_cancer = pd.read_csv("/Users/maddiemann/Documents/MATH-4025-sp26/Math-4025-Project-Maddie-Mann/Data/prad_tcga_pan_can_atlas_2018_clinical_data.tsv", sep='\t')

In [12]:
prostate_cancer.head()

,Study ID,Patient ID,Sample ID,Diagnosis Age,Neoplasm Disease Stage American Joint Committee on Cancer Code,American Joint Committee on Cancer Publication Version Type,Aneuploidy Score,Buffa Hypoxia Score,Cancer Type,TCGA PanCanAtlas Cancer Type Acronym,...,Tumor Break Load,Tissue Prospective Collection Indicator,Tissue Retrospective Collection Indicator,Tissue Source Site,Tissue Source Site Code,TMB (nonsynonymous),Tumor Disease Anatomic Site,Tumor Type,Patient Weight,Winter Hypoxia Score
0,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VL,TCGA-2A-A8VL-01,51,NaN,NaN,0.0,-27.0,Prostate Cancer,PRAD,...,50.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.7,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-34.0
1,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VO,TCGA-2A-A8VO-01,57,NaN,NaN,0.0,-29.0,Prostate Cancer,PRAD,...,32.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.9,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-26.0
2,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VT,TCGA-2A-A8VT-01,47,NaN,NaN,14.0,-39.0,Prostate Cancer,PRAD,...,29.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.3,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-42.0
3,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VV,TCGA-2A-A8VV-01,52,NaN,NaN,0.0,-25.0,Prostate Cancer,PRAD,...,25.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.8,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-36.0
4,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VX,TCGA-2A-A8VX-01,70,NaN,NaN,2.0,NaN,Prostate Cancer,PRAD,...,149.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.0,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,NaN

In [13]:
prostate_cancer.columns = prostate_cancer.columns.str.replace(' ', '_')

In [14]:
prostate_cancer.head()

,Study_ID,Patient_ID,Sample_ID,Diagnosis_Age,Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code,American_Joint_Committee_on_Cancer_Publication_Version_Type,Aneuploidy_Score,Buffa_Hypoxia_Score,Cancer_Type,TCGA_PanCanAtlas_Cancer_Type_Acronym,...,Tumor_Break_Load,Tissue_Prospective_Collection_Indicator,Tissue_Retrospective_Collection_Indicator,Tissue_Source_Site,Tissue_Source_Site_Code,TMB_(nonsynonymous),Tumor_Disease_Anatomic_Site,Tumor_Type,Patient_Weight,Winter_Hypoxia_Score
0,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VL,TCGA-2A-A8VL-01,51,NaN,NaN,0.0,-27.0,Prostate Cancer,PRAD,...,50.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.7,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-34.0
1,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VO,TCGA-2A-A8VO-01,57,NaN,NaN,0.0,-29.0,Prostate Cancer,PRAD,...,32.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.9,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-26.0
2,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VT,TCGA-2A-A8VT-01,47,NaN,NaN,14.0,-39.0,Prostate Cancer,PRAD,...,29.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.3,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-42.0
3,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VV,TCGA-2A-A8VV-01,52,NaN,NaN,0.0,-25.0,Prostate Cancer,PRAD,...,25.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.8,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,-36.0
4,prad_tcga_pan_can_atlas_2018,TCGA-2A-A8VX,TCGA-2A-A8VX-01,70,NaN,NaN,2.0,NaN,Prostate Cancer,PRAD,...,149.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.0,Prostate,"Prostate Adenocarcinoma, Acinar Type",NaN,NaN

In [29]:
non_predictor = ['Study_ID', 'Patient_ID', 'Sample_ID', 'Tumor_Type', 'Patient_Weight', 'Sex', 'Number_of_Samples_Per_Patient', 'American_Joint_Committee_on_Cancer_Metastasis_Stage_Code', 'Primary_Lymph_Node_Presentation_Assessment', 'Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code', 'American_Joint_Committee_on_Cancer_Publication_Version_Type']

In [24]:
prostate_cancer['Patient_Weight'].isna().sum()

np.int64(494)

In [21]:
prostate_cancer.describe()

,Diagnosis_Age,Neoplasm_Disease_Stage_American_Joint_Committee_on_Cancer_Code,American_Joint_Committee_on_Cancer_Publication_Version_Type,Aneuploidy_Score,Buffa_Hypoxia_Score,Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date,Birth_from_Initial_Pathologic_Diagnosis_Date,Last_Alive_Less_Initial_Pathologic_Diagnosis_Date_Calculated_Day_Value,Disease_Free_(Months),Months_of_disease-specific_survival,...,Overall_Survival_(Months),American_Joint_Committee_on_Cancer_Metastasis_Stage_Code,Progress_Free_Survival_(Months),Primary_Lymph_Node_Presentation_Assessment,Ragnum_Hypoxia_Score,Number_of_Samples_Per_Patient,Tumor_Break_Load,TMB_(nonsynonymous),Patient_Weight,Winter_Hypoxia_Score
count,494.000000,0.0,0.0,471.000000,333.000000,486.000000,483.000000,463.0,334.000000,494.000000,...,494.000000,0.0,494.000000,0.0,333.000000,494.0,491.000000,494.000000,0.0,333.000000
mean,61.022267,NaN,NaN,2.528662,-26.627628,1080.135802,-22486.853002,0.0,35.656569,35.731337,...,35.731337,NaN,31.661258,NaN,-18.402402,1.0,76.648676,1.561606,NaN,-30.840841
std,6.844070,NaN,NaN,4.023697,8.810219,783.439310,2486.124360,0.0,24.411817,25.967482,...,25.967482,NaN,24.941887,NaN,6.183460,0.0,105.879819,9.490350,NaN,11.925038
min,41.000000,NaN,NaN,0.000000,-43.000000,0.000000,-28721.000000,0.0,1.873952,0.756156,...,0.756156,NaN,0.756156,NaN,-28.000000,1.0,0.000000,0.000000,NaN,-62.000000
25%,56.000000,NaN,NaN,0.000000,-33.000000,517.500000,-24293.500000,0.0,19.413486,17.227208,...,17.227208,NaN,13.832725,NaN,-22.000000,1.0,25.000000,0.675000,NaN,-38.000000
50%,61.000000,NaN,NaN,1.000000,-29.000000,924.000000,-22626.000000,0.0,30.328435,30.377749,...,30.377749,NaN,25.692869,NaN,-20.000000,1.0,53.000000,0.900000,NaN,-32.000000
75%,66.000000,NaN,NaN,3.000000,-21.000000,1463.250000,-20746.500000,0.0,45.665253,48.106322,...,48.106322,NaN,44.794030,NaN,-16.000000,1.0,90.000000,1.200000,NaN,-24.000000
max,78.000000,NaN,NaN,26.000000,11.000000,5024.000000,-15330.000000,0.0,165.170793,165.170793,...,165.170793,NaN,165.170793,NaN,20.000000,1.0,1135.000000,208.633333,NaN,22.000000

Certain columns were dropped before data splitting because they only contained NA values, had little or no variance, or were not useful for predicting.

### Notes about features 
- Aneuploidy score: measures the total number of chromosome arm gains or losses within a tumor. Ranges from 0-39. A higher score indicates more "chaos" in the genome and often more aggressive tumors. 
- Birth_from_Initial_Pathologic_Diagnosis_Date: Time interval from a person's date of birth to the date of initial pathologic diagnosis, represented as a calculated number of days.

New_Neoplasm_Event_Post_Initial_Therapy_Indicator: Time interval from a person's date of birth to the date of initial pathologic diagnosis, represented as a calculated number of days.

Neoplasm_Disease_Lymph_Node_Stage_American_Joint_Committee_on_Cancer_Code: The codes that represent the stage of cancer based on the nodes present (N stage) according to criteria based on multiple editions of the AJCC's Cancer Staging Manual.

Buffa_Hypoxia_Score: a molecular tool used to quantify the level of oxygen deprivation (hypoxia) within tumors. Measures the activity of genes regulated by low oxygen, high scores are associated with poorer prognosis 

Ragnum_Hypoxia_Score: Measures oxygenation levels particularly in prostate cancer.

Disease_Free_(Months): Amount of time in remission. Likely will be predictor variable

In [28]:
prostate_cancer.drop(columns =non_predictor)

,Diagnosis_Age,American_Joint_Committee_on_Cancer_Publication_Version_Type,Aneuploidy_Score,Buffa_Hypoxia_Score,Cancer_Type,TCGA_PanCanAtlas_Cancer_Type_Acronym,Cancer_Type_Detailed,Last_Communication_Contact_from_Initial_Pathologic_Diagnosis_Date,Birth_from_Initial_Pathologic_Diagnosis_Date,Last_Alive_Less_Initial_Pathologic_Diagnosis_Date_Calculated_Day_Value,...,Somatic_Status,Subtype,Tumor_Break_Load,Tissue_Prospective_Collection_Indicator,Tissue_Retrospective_Collection_Indicator,Tissue_Source_Site,Tissue_Source_Site_Code,TMB_(nonsynonymous),Tumor_Disease_Anatomic_Site,Winter_Hypoxia_Score
0,51,NaN,0.0,-27.0,Prostate Cancer,PRAD,Prostate Adenocarcinoma,621.0,-18658.0,0.0,...,Matched,PRAD,50.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.700000,Prostate,-34.0
1,57,NaN,0.0,-29.0,Prostate Cancer,PRAD,Prostate Adenocarcinoma,1701.0,-20958.0,0.0,...,Matched,PRAD,32.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.900000,Prostate,-26.0
2,47,NaN,14.0,-39.0,Prostate Cancer,PRAD,Prostate Adenocarcinoma,1373.0,-17365.0,0.0,...,Matched,PRAD,29.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.300000,Prostate,-42.0
3,52,NaN,0.0,-25.0,Prostate Cancer,PRAD,Prostate Adenocarcinoma,671.0,-19065.0,0.0,...,Matched,PRAD,25.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,0.800000,Prostate,-36.0
4,70,NaN,2.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,1378.0,-25904.0,0.0,...,Matched,PRAD,149.0,No,Yes,Memorial Sloan Kettering Cancer Center,2A,1.000000,Prostate,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
489,65,NaN,20.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,547.0,-24030.0,0.0,...,Matched,PRAD,115.0,No,Yes,University Medical Center Hamburg-Eppendorf,ZG,1.100000,Prostate,NaN
490,69,NaN,2.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,455.0,-25477.0,0.0,...,Matched,PRAD,50.0,No,Yes,University Medical Center Hamburg-Eppendorf,ZG,0.933333,Prostate,NaN
491,73,NaN,18.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,349.0,-26902.0,0.0,...,Matched,PRAD,135.0,No,Yes,University Medical Center Hamburg-Eppendorf,ZG,1.600000,Prostate,NaN
492,55,NaN,2.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,410.0,-20428.0,0.0,...,Matched,PRAD,135.0,No,Yes,University Medical Center Hamburg-Eppendorf,ZG,0.833333,Prostate,NaN
493,73,NaN,7.0,NaN,Prostate Cancer,PRAD,Prostate Adenocarcinoma,132.0,-26697.0,0.0,...,Matched,PRAD,54.0,No,Yes,University Medical Center Hamburg-Eppendorf,ZG,2.766667,Prostate,NaN